package Utils;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.Locale;
import java.util.Map;
import java.util.regex.Pattern;

import static org.junit.jupiter.api.Assertions.*;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

/**
 * Validates {@link FragmentedMp4Seeker} against a real 10-second fragmented MP4 generated by
 * ffmpeg ({@code -movflags frag_keyframe+empty_moov+default_base_moof}).
 * The whole class is skipped via JUnit Assumptions when ffmpeg is not on the system PATH.
 */
public class FragmentedMp4SeekerTest {

    private static Path sampleFile;
    private static Path tempDir;

    @BeforeAll
    static void generateSample() throws Exception {
        String ffmpeg = findFfmpeg();
        assumeTrue(ffmpeg != null, "ffmpeg not found on PATH - skipping FragmentedMp4SeekerTest");

        tempDir = Files.createTempDirectory("fmp4seeker");
        sampleFile = tempDir.resolve("sample.mp4");

        ProcessBuilder pb = new ProcessBuilder(
                ffmpeg,
                "-y",
                "-f", "lavfi", "-i", "testsrc2=duration=10:size=320x240:rate=24",
                "-f", "lavfi", "-i", "sine=frequency=440:duration=10",
                "-c:v", "libx264", "-pix_fmt", "yuv420p", "-g", "24",
                "-c:a", "aac", "-shortest",
                "-movflags", "frag_keyframe+empty_moov+default_base_moof",
                "-f", "mp4",
                sampleFile.toString());
        pb.redirectErrorStream(true);
        Process process = pb.start();
        try (BufferedReader reader = new BufferedReader(
                new InputStreamReader(process.getInputStream(), StandardCharsets.UTF_8))) {
            while (reader.readLine() != null) {
                // drain ffmpeg output
            }
        }
        int exit = process.waitFor();
        assumeTrue(exit == 0, "ffmpeg failed with exit code " + exit);
        assumeTrue(Files.isRegularFile(sampleFile) && Files.size(sampleFile) > 0,
                "ffmpeg produced no output file");
    }

    @AfterAll
    static void cleanup() throws Exception {
        if (tempDir == null) {
            return;
        }
        try (var paths = Files.walk(tempDir)) {
            for (Path p : paths.sorted(Comparator.reverseOrder()).toList()) {
                Files.deleteIfExists(p);
            }
        }
    }

    /** Locates the ffmpeg executable on the system PATH (ffmpeg.exe on Windows). */
    private static String findFfmpeg() {
        String os = System.getProperty("os.name", "").toLowerCase(Locale.ROOT);
        String name = os.contains("win") ? "ffmpeg.exe" : "ffmpeg";
        String pathEnv = System.getenv("PATH");
        if (pathEnv == null) {
            return null;
        }
        for (String dir : pathEnv.split(Pattern.quote(java.io.File.pathSeparator))) {
            if (dir.isEmpty()) {
                continue;
            }
            Path candidate = Path.of(dir, name);
            if (Files.isRegularFile(candidate)) {
                return candidate.toString();
            }
        }
        return null;
    }

    @Test
    void firstFragmentOffsetIsPastHeaderRegion() throws IOException {
        long first = FragmentedMp4Seeker.firstFragmentOffset(sampleFile);
        assertTrue(first > 0, "firstFragmentOffset should be > 0, got " + first);
    }

    @Test
    void byteOffsetForTimeIsNonNullNonDecreasing() throws IOException {
        double[] times = {0.0, 5.0, 9.5};
        long first = FragmentedMp4Seeker.firstFragmentOffset(sampleFile);
        Long previous = null;
        for (double t : times) {
            Long off = FragmentedMp4Seeker.byteOffsetForTime(sampleFile, t);
            assertNotNull(off, "byteOffsetForTime(" + t + ") should not be null");
            assertTrue(off >= first,
                    "byteOffsetForTime(" + t + ")=" + off + " should be >= firstFragmentOffset=" + first);
            if (previous != null) {
                assertTrue(off >= previous,
                        "byteOffsetForTime must be monotonically non-decreasing: " + previous + " -> " + off);
            }
            previous = off;
        }
    }

    @Test
    void byteOffsetForTimeBeyondWrittenEndIsNull() throws IOException {
        assertNull(FragmentedMp4Seeker.byteOffsetForTime(sampleFile, 999.0),
                "target far beyond the written end must map to null");
    }

    @Test
    void endTimeSecondsApproximatesDuration() throws IOException {
        double end = FragmentedMp4Seeker.endTimeSeconds(sampleFile);
        assertEquals(10.0, end, 1.0, "end time should be ~10s, got " + end);
    }

    @Test
    void truncateLengthAtTimeIsSane() throws IOException {
        long first = FragmentedMp4Seeker.firstFragmentOffset(sampleFile);
        Long cut = FragmentedMp4Seeker.byteOffsetForTime(sampleFile, 5.0);
        assertNotNull(cut, "byteOffsetForTime(5.0) should not be null");
        long trunc = FragmentedMp4Seeker.truncateLengthAtTime(sampleFile, 5.0);
        assertTrue(trunc >= first,
                "truncateLengthAtTime(5.0)=" + trunc + " should be >= firstFragmentOffset=" + first);
        assertTrue(trunc <= cut,
                "truncateLengthAtTime(5.0)=" + trunc + " should be <= byteOffsetForTime(5.0)=" + cut);
    }

    @Test
    void readTrackTimescalesHasPositiveVideoTimescale() throws IOException {
        Map<Integer, Integer> timescales = FragmentedMp4Seeker.readTrackTimescales(sampleFile);
        assertFalse(timescales.isEmpty(), "track timescales should not be empty");
        assertTrue(timescales.values().stream().allMatch(ts -> ts > 0),
                "all track timescales must be positive");
    }

    @Test
    void copyFragmentsShiftedMovesTimelineByDelta() throws IOException {
        double delta = 5.0;
        long first = FragmentedMp4Seeker.firstFragmentOffset(sampleFile);
        Map<Integer, Integer> timescales = FragmentedMp4Seeker.readTrackTimescales(sampleFile);
        Path shifted = tempDir.resolve("shifted.mp4");
        try (InputStream in = Files.newInputStream(sampleFile);
             OutputStream out = Files.newOutputStream(shifted)) {
            byte[] buf = new byte[8192];
            long remaining = first;
            while (remaining > 0) {
                int n = in.read(buf, 0, (int) Math.min(buf.length, remaining));
                if (n < 0) {
                    throw new IOException("Unexpected EOF copying header of " + sampleFile);
                }
                out.write(buf, 0, n);
                remaining -= n;
            }
            FragmentedMp4Seeker.copyFragmentsShifted(sampleFile, first,
                    Files.size(sampleFile) - first, delta, timescales, out, first);
        }
        for (double t : new double[]{0.5, 2.0, 5.0, 7.0}) {
            Long expected = FragmentedMp4Seeker.byteOffsetForTime(sampleFile, t);
            Long actual = FragmentedMp4Seeker.byteOffsetForTime(shifted, t + delta);
            assertNotNull(expected, "sample byteOffsetForTime(" + t + ") should not be null");
            assertEquals(expected, actual,
                    "shifted timeline must resolve t+delta to the same byte offset as t");
        }
        double sampleEnd = FragmentedMp4Seeker.endTimeSeconds(sampleFile);
        double shiftedEnd = FragmentedMp4Seeker.endTimeSeconds(shifted);
        assertEquals(sampleEnd + delta, shiftedEnd, 0.5,
                "shifted end time must grow by the delta");
    }
}
